# Generated by Django 4.0 on 2022-03-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
