# Generated by Django 4.0 on 2022-03-14 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notice_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
