# Generated by Django 4.1 on 2022-10-02 06:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='update',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
